### ISSUE TITLE
Support of Intercom Mobile SDK version 6

### ISSUE THREAD

**Issue by kgouraw** [nventive/Binding.Intercom#10]
Intercom is deprecating support of SDK 5 or below at end of June this year. Any plan for upgrading it to support new SDK version 6.0 support?

**Comment by MatFillion** [comment]
Hey @kgouraw 👋 

Update is not planned at the moment but we would be happy to accept a pull request !

**Comment by guillermo-gerard** [comment]
I'm doing a binding to 6.1.0 and resolved all the build problems so far, but now I'm facing a runtime error when trying to use the messenger: I cannot attach any gif/image, the app crashes with:
```
Java.Lang.NoSuchMethodError
  Message=No virtual method getUri()Landroid/net/Uri; in class Lcom/intercom/input/gallery/GalleryImage; or its super classes
```

```
Java.Lang.NoSuchMethodError
  Message=No virtual method withUri(Landroid/net/Uri;)Lcom/intercom/input/gallery/GalleryImage$Builder; in class Lcom/intercom/input/gallery/GalleryImage$Builder; or its super classes
```

Any clues?

**Comment by guillermo-gerard** [comment]
I've resolved the problem: it appears that they forgot a commit in the official repository: those two methods from my last comment are not there in the version 2.0.2 of the android gallery composer:
![image](https://user-images.githubusercontent.com/50535806/77259050-83f74480-6c5d-11ea-9219-e640f509d999.png)
I've found this version (version: unspecified! :D ) 
`https://mvnrepository.com/artifact/com.intercom/android-composer-gallery/unspecified`
which appears to be newer and it has those methods and works with my code

**Comment by jeremiethibeault** [comment]
Hi @guillermo-gerard we updated the SDK to version 5.1.6 to have Android 9 support. As June 30th is coming, if you want to create a PR that updates it to version 6.* we'll be happy to merge it.

Thanks

**Comment by guillermo-gerard** [comment]
Hi @jeremiethibeault , I've just post a comment in #12
I think that @HamzaRabah can fix his PR simply by adding the android-composer-gallery-2.0.2.aar I'm mentioning in my comment above, if that doesn't work I can create a PR for you to test and merge, of course, just let me know how it goes.
