### ISSUE TITLE
Updating to v9

### ISSUE THREAD

**Issue by katkusmt** [nventive/Binding.Intercom#14]
Hello, any plans to update the bindings to v9?

There are some issues with permission on previous releases and also this version is about to be deprecated.

**Comment by vincentcastagna** [comment]
Hello @katkusmt  we are currently working on an update for iOS to 9.3.1.

Android update will come soon after :)

**Comment by GuillaumeSE** [comment]
the NuGet package for IOS is available for intercom 9.3.1
https://www.nuget.org/packages/nventive.Binding.Intercom/4.1.16-dev0013

**Comment by vincentcastagna** [comment]
Version stated my guillaume is the first draft we were binding to sdk simulator (not working on real devices). 

The correct nuget is : https://www.nuget.org/packages/nventive.Binding.Intercom/4.1.17-dev0017

**Comment by vincentcastagna** [comment]
Updates are now done for both platforms, check release 5.0.0 available on [nuget](https://www.nuget.org/packages/nventive.Binding.Intercom/5.0.0).
