### ISSUE TITLE
Uploading to AppStore is failed (v5.0.0)

### ISSUE THREAD

**Issue by alexshikov** [nventive/Binding.Intercom#24]
The build seems working ok locally on the device.  
But our CI fails to upload the build with errors:
```
ERROR ITMS-90680: "Invalid directory. The bundle Payload/OurApp.iOS.app/Intercom.framework is not contained in a correctly named directory. It should be under "Frameworks"."
ERROR ITMS-90085: "No architectures in the binary. Lipo failed to detect any architectures in the bundle executable."
```

Our stack on the CI is:
- macOS 10.14.4 (Mojave)
- Xcode 12.4 (Build version 12D4e)
- Visual Studio release-8.9
- Xamarin.iOS 14.14.2.5

**Comment by ignasbagdonas** [comment]
yes, we have the same issue. It's blocker!

**Comment by vincentcastagna** [comment]
Hello all,

This should be fixed with this [PR](https://github.com/nventive/Binding.Intercom/pull/26), i.e fututre 5.0.1 version
