### ISSUE TITLE
Safe area insets doesn't work on iPhone X

### ISSUE THREAD

**Issue by pawelwojtasiak** [nventive/Binding.Intercom#9]
Hey, I am using ur binding lib for my project and I noticed that on iPhone X , iPhone Xs ( generally those with notch)  chat view is behind the notch that means I can't close the presenter cuz "X" is covered by system indicators (clock, battery life etc.)
 
Do you know how it could be fixed ?
Thanks :)

**Comment by MatFillion** [comment]
Hey @pawelwojtasiak  👋 

The native library must handle that on its own, as this is simply a binding. Odds are an updated version of the library would solve the problem, but you should search https://developers.intercom.com if that's an issue that was solved in later versions.

This binding is currently based off Intercom 4.17.

**Comment by MatFillion** [comment]
Issue #10 could potentially solve this at the same time.

**Comment by kgouraw** [comment]
@pawelwojtasiak and @MatFillion, currently I don't have any layout issue on newer version of iPhone. Make sure you are using below XAML namespace with  UseSafeArea="True":
   xmlns:ios="clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core"
                ios:Page.UseSafeArea="True"
